import type { Exercise } from "@titan/domain/exercise";

/**
 * Every movement referenced by the four initial programs. Exercises are shared,
 * global entities; a program references them by id and never embeds progression
 * logic (that lives on the slot's policy).
 */
export const exercises: readonly Exercise[] = [
  {
    id: "back-squat",
    isUnilateral: false,
    modality: "barbell",
    movementPattern: "squat",
    name: "Back Squat",
  },
  {
    id: "romanian-deadlift",
    isUnilateral: false,
    modality: "barbell",
    movementPattern: "hinge",
    name: "Romanian Deadlift",
  },
  {
    id: "bulgarian-split-squat",
    isUnilateral: true,
    modality: "dumbbell",
    movementPattern: "lunge",
    name: "Bulgarian Split Squat",
  },
  {
    id: "standing-calf-raise",
    isUnilateral: false,
    modality: "machine",
    movementPattern: "calf",
    name: "Standing Calf Raise",
  },
  {
    id: "plank",
    isUnilateral: false,
    modality: "bodyweight",
    movementPattern: "core",
    name: "Plank",
  },
  {
    id: "rower",
    isUnilateral: false,
    modality: "rower",
    movementPattern: "cardio",
    name: "Rower",
  },
  {
    id: "bench-press",
    isUnilateral: false,
    modality: "barbell",
    movementPattern: "horizontal-push",
    name: "Bench Press",
  },
  {
    id: "weighted-pullup",
    isUnilateral: false,
    modality: "bodyweight",
    movementPattern: "vertical-pull",
    name: "Weighted Pull-Up",
  },
  {
    id: "overhead-press",
    isUnilateral: false,
    modality: "barbell",
    movementPattern: "vertical-push",
    name: "Standing Overhead Press",
  },
  {
    id: "barbell-row",
    isUnilateral: false,
    modality: "barbell",
    movementPattern: "horizontal-pull",
    name: "Barbell Row",
  },
  {
    id: "dips",
    isUnilateral: false,
    modality: "bodyweight",
    movementPattern: "vertical-push",
    name: "Dips",
  },
  {
    id: "ab-wheel",
    isUnilateral: false,
    modality: "bodyweight",
    movementPattern: "core",
    name: "Ab Wheel Rollout",
  },
  {
    id: "deadlift",
    isUnilateral: false,
    modality: "barbell",
    movementPattern: "hinge",
    name: "Deadlift",
  },
  {
    id: "push-press",
    isUnilateral: false,
    modality: "barbell",
    movementPattern: "vertical-push",
    name: "Push Press",
  },
  {
    id: "farmer-carry",
    isUnilateral: false,
    modality: "dumbbell",
    movementPattern: "carry",
    name: "Farmer Carry",
  },
  {
    id: "burpee",
    isUnilateral: false,
    modality: "bodyweight",
    movementPattern: "conditioning",
    name: "Burpee",
  },
  {
    id: "dumbbell-swing",
    isUnilateral: false,
    modality: "dumbbell",
    movementPattern: "hinge",
    name: "Dumbbell Swing",
  },
  {
    id: "pushup",
    isUnilateral: false,
    modality: "bodyweight",
    movementPattern: "horizontal-push",
    name: "Push-Up",
  },
  {
    id: "walking-lunge",
    isUnilateral: true,
    modality: "bodyweight",
    movementPattern: "lunge",
    name: "Walking Lunge",
  },
  {
    id: "side-plank",
    isUnilateral: true,
    modality: "bodyweight",
    movementPattern: "core",
    name: "Side Plank",
  },
  {
    id: "run",
    isUnilateral: false,
    modality: "run",
    movementPattern: "cardio",
    name: "Run",
  },
  {
    id: "hill-sprint",
    isUnilateral: false,
    modality: "run",
    movementPattern: "conditioning",
    name: "Hill Sprint",
  },
  {
    id: "bike",
    isUnilateral: false,
    modality: "bike",
    movementPattern: "cardio",
    name: "Bike",
  },
  {
    id: "hike",
    isUnilateral: false,
    modality: "hike",
    movementPattern: "cardio",
    name: "Hike",
  },
];
